application: invoice-jesse
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: invoice.py

libraries:
- name: webapp2
  version: "2.5.2"
